name: Reusable - Build & Push Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      docker_context:
        required: false
        type: string
        default: ./app
    outputs:
      digest:
        description: Image digest pushed to ECR
        value: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    outputs:
      digest: ${{ steps.buildpush.outputs.digest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credential (OIDC)
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push (with cache)
        id: buildpush
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.docker_context }}
          push: true
          tags: |
            ${{ secrets.ECR_REPOSITORY_URL }}:${{ github.sha }}
            ${{ secrets.ECR_REPOSITORY_URL }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
